version: "3.8"

services:
  app:
    build: .
    container_name: shelvy_ui
    ports:
      - "8080:80"         # React/nginx
    depends_on:
      - api

  api:
    build:
      context: ./backend
    container_name: shelvy_backend
    environment:
      MONGO_URL: mongodb://root:password@mongo:27017
      MONGO_DB: shelvy
    ports:
      - "8000:8000"       # FastAPI
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: shelvy
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
